### ISSUE TITLE
我是原作者，兄弟请删除uniappStage这个仓库谢谢，该仓库存在个人隐私，删除必重谢，联系方式 21407092@qq.com QQ 21407092

### ISSUE THREAD

**Issue by ghost** [rootkiter/Binary-files#4]
我是原作者，兄弟请删除uniappStage这个仓库谢谢，该仓库存在个人隐私，删除必重谢，联系方式 21407092@qq.com QQ 21407092

**Comment by rootkiter** [comment]
？

**Comment by ufofly** [comment]
我是秦始皇，打钱！

**Comment by ghost** [comment]
屎皇帝，你好，我邮件发错了，不好意思打扰了你休息了，你钻回去继续睡吧




***@***.***
 
发件人： chens
发送时间： 2023-07-28 14:36
收件人： rootkiter/Binary-files
抄送： 请删除仓库uniappStage,万分谢谢; Author
主题： Re: [rootkiter/Binary-files] 我是原作者，兄弟请删除uniappStage这个仓库谢谢，该仓库存在个人隐私，删除必重谢，联系方式 ***@***.*** QQ 21407092 (Issue #4)
我是秦始皇，打钱！

**Comment by rootkiter** [comment]
所以重谢呢...我反正已经删除了[狗头]

**Comment by ghost** [comment]
送你一对兵马俑，自提






***@***.***
 
发件人： rootkiter
发送时间： 2023-07-28 15:19
收件人： rootkiter/Binary-files
抄送： 请删除仓库uniappStage,万分谢谢; Author
主题： Re: [rootkiter/Binary-files] 我是原作者，兄弟请删除uniappStage这个仓库谢谢，该仓库存在个人隐私，删除必重谢，联系方式 ***@***.*** QQ 21407092 (Issue #4)
所以重谢呢...我反正已经删除了[狗头]
